### PR TITLE
Cookie - category

### PR DESCRIPTION
**Pull request by lakshankd**
PR for cookie-category branch

### CODE REVIEW

**Comment by pavinduLakshan** [comment]
@lakshankd , seems like there are some merge conflicts. Ping me if you are unable to resolve them on your own.

**Comment by lakshankd** [comment]
> @lakshankd , seems like there are some merge conflicts. Ping me if you are unable to resolve them on

**Review by nimeshnuwanga — APPROVED** [review]

**Comment by pavinduLakshan** [comment]
@lakshankd Why this is merged without addressing any of the comments :/ ?

**Comment by pavinduLakshan** [comment]
Please send a follow-up PR to address the review comments.

**Pull request merged**
